application: static
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /img
  static_dir: frontend/img
- url: /js
  static_dir: frontend/js
- url: /css
  static_dir: frontend/css

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"
